homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: 48
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  customize: !include customize.yaml
  unit_system: imperial

group: !include group.yaml
zone: !include zones.yaml
script: !include script.yaml

recorder:
  purge_days: 14
  db_url: !secret recorder_db_url

logger:
  default: warn
  logs:
    homeassistant.components.mqtt: debug
    homeassistant.components.device_tracker.owntracks: debug
    homeassistant.components.proximity: debug
    homeassistant.components.zwave: info
    homeassistant.components.automation: info
#    homeassistant.components.sensor.aeotec_zw096_smart_switch_6_power_15: info

# Discover some devices automatically
discovery:

# Web UI
http:
        server_port: 8123
        ssl_certificate: !secret http_ssl_certificate
        ssl_key: !secret http_ssl_key
#        api_password: !secret http_api_password
#        use_x_forwarded_for: true
#        trusted_networks:
#          - 10.0.1.0/24
#          - 127.0.0.1
#          - ::1
#
mqtt:
        broker: !secret mqtt_broker
        port: !secret mqtt_port
        client_id: !secret mqtt_client_id
        keepalive: 300
        username: !secret mqtt_username
        password: !secret mqtt_password
        protocol: 3.1
        certificate: /home/hass/home-assistant/config/identrust-root-and-lets-encrypt-x3.pem

device_tracker owntracks:
  platform: owntracks
  max_gps_accuracy: 250
  track_new_devices: no
 
#device_tracker nmap:
#  platform: nmap_tracker
#  hosts: 10.0.1.1/24
#  interval_seconds: 119
#  track_new_devices: no
#  # Seconds to wait till marking someone as not home after not being seen (default: 180)
#  consider_home: 600
#  # Minutes to exclude devices from a scan while they are home
#  home_interval: 5

sensor: !include sensor.yaml

# Checks for available updates
#updater:

automation: !include_dir_merge_list automation/

# Enables support for tracking state changes over time.
#history:
influxdb:
  host: !secret influxdb_host
  ssl: true
  port: 8085
  username: !secret influxdb_username
  password: !secret influxdb_password
  whitelist:
    - sensor.cpu_temperature
    - sensor.stelpro_stzw402_electronic_thermostat_temperature_11
    - sensor.bed_therm_setting
    - sensor.to_work_in
    - sensor.pws_feelslike_f
    - group.bedroom_lights
    - group.kitchen_lights
    - sensor.cpu_use
    - sensor.ram_use
    - sensor.disk_use_
    - sensor.swap_use
    - proximity.home
    - sensor.aeotec_zw096_smart_switch_6_energy_14
    - sensor.aeotec_zw096_smart_switch_6_power_14
    - sensor.aeotec_zw096_smart_switch_6_energy_15
    - sensor.aeotec_zw096_smart_switch_6_power_15

# Enables the frontend
frontend:

# View all events in a logbook
logbook:

# Show links to resources in log and frontend
#introduction:

# Allows you to issue voice commands from the frontend
#conversation:

# Track the sun
sun:

media_player:
  platform: sonos
  interface_addr: 10.0.1.3
  hosts: 
        - 10.0.1.60 # Kitchen

zwave:
  usb_path: /dev/zwave
 # config_path: /home/hass/home-assistant/lib/python3.4/site-packages/libopenzwave-0.3.0b8-py3.4-linux-x86_64.egg/config
  config_path: /home/hass/home-assistant/lib/python3.5/site-packages/libopenzwave-0.3.1-py3.5-linux-x86_64.egg/config
  polling_interval: 123456
  autoheal: false
  device_config:
    light.linear_unknown_type4754_id3038_level_2:
      polling_intensity: 1
      refresh_value: true
      delay: 5
    light.bedroomdressersw_level_20:
      polling_intensity: 1
      refresh_value: true
      delay: 5
    light.bedroomdeskswitc_level_21:
      polling_intensity: 1
      refresh_value: true
      delay: 5
    light.linear_lb60z1_dimmable_led_light_bulb_level_19:
      polling_intensity: 1
      refresh_value: true
      delay: 5
    light.linear_lb60z1_dimmable_led_light_bulb_level_22:
      polling_intensity: 1
      refresh_value: true
      delay: 5
    sensor.aeotec_zw096_smart_switch_6_energy_14:
      polling_intensity: 4
    sensor.aeotec_zw096_smart_switch_6_power_14:
      polling_intensity: 4
    sensor.aeotec_zw096_smart_switch_6_energy_15:
      polling_intensity: 4
    sensor.aeotec_zw096_smart_switch_6_power_15:
      polling_intensity: 4
    sensor.vision_zp3111_multisensor_4in1_burglar_26:
      polling_intensity: 2
    sensor.vision_zp3111_multisensor_4in1_luminance_26:
      polling_intensity: 2
    sensor.vision_zp3111_multisensor_4in1_relative_humidity_26:
      polling_intensity: 2
    sensor.vision_zp3111_multisensor_4in1_temperature_26:
      polling_intensity: 2

notify:
  name: email
  platform: smtp
  server: localhost
  port: 25
  sender: !secret notify_sender
  recipient: !secret notify_recipient

# Weather radar from Weather Underground. Retrieved via cron
# https://community.home-assistant.io/t/is-anyone-doing-anything-with-weather-underground/763/101
camera:
    platform: local_file
    file_path: /home/hass/weather.gif
    name: Recent Radar

input_boolean: !include input_boolean.yaml

proximity:
  home:
    ignored_zones:
      - work
    devices:
      - !secret device_tracker_1
    tolerance: 250
#  unit_of_measurement: mi

panel_iframe:
  monitoring:
    title: Monitoring
    url: !secret monitor_url
    icon: mdi:bell
  hagraphs:
    title: Graphs
    url: !secret weblink_grafana_ha
    icon: mdi:chart-line
  systemgraphs:
    title: System Graphs
    url: !secret weblink_grafana_sys
    icon: mdi:chart-areaspline
