homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: 48
  # C for Celcius, F for Fahrenheit
  temperature_unit: F
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  customize: !include customize.yaml

group: !include group.yaml
zone: !include zones.yaml
script: !include script.yaml

recorder:
  purge_days: 14
  db_url: !secret recorder_db_url

logger:
  default: info
  logs:
    homeassistant.components.device_tracker.mqtt: debug

# Discover some devices automatically
discovery:

# Web UI
http:
        server_port: 8123
        ssl_certificate: !secret http_ssl_certificate
        ssl_key: !secret http_ssl_key
#        api_password: !secret http_api_password

mqtt:
        broker: !secret mqtt_broker
        port: !secret mqtt_port
        client_id: !secret mqtt_client_id
        keepalive: 300
        username: !secret mqtt_username
        password: !secret mqtt_password
        protocol: 3.1
        certificate: /home/hass/home-assistant/config/comodorsacertificationauthority.crt

device_tracker owntracks:
  platform: owntracks
  max_gps_accuracy: 200
  track_new_devices: no
 
#device_tracker nmap:
#  platform: nmap_tracker
#  hosts: 10.0.1.1/24
#  interval_seconds: 119
#  track_new_devices: no
#  # Seconds to wait till marking someone as not home after not being seen (default: 180)
#  consider_home: 600
#  # Minutes to exclude devices from a scan while they are home
#  home_interval: 5

sensor: !include sensor.yaml

# Checks for available updates
updater:

automation: !include automation.yaml

# Enables support for tracking state changes over time.
#history:
influxdb:
  host: 127.0.0.1
  username: !secret influxdb_username
  password: !secret influxdb_password
  blacklist:
    - sensor.weather_summary
    - sensor.weather_hourly_summary
    - sensor.next24
    - sun.sun
    - updater.updater
    - weblink.graphs
    - weblink.system_graphs
    - zone.home
    - zone.work
    - media_player.kitchen
    - script.away
    - script.get_home_sunset
    - script.heat_bed
    - script.heat_occupied
    - script.home
    - script.kitchen_off
    - sensor.date__time
    - group.all_devices
    - group.all_lights
    - group.all_lights_2
    - group.default_view
    - group.lights
    - group.people
    - group.toggles
    - group.system_info
    - input_boolean.automation_override
    - input_boolean.vacation
    - light.__level_2
    - light.__level_10
    - light.__level_5
    - light.__level_6
    - light.linear_unknown_type4754_id3038_level_2
    - light.linear_unknown_type4754_id3038_level_5
    - light.linear_unknown_type4754_id3038_level_6
    - light.linear_unknown_type4754_id3038_level_10
    - camera.recent_radar
    - sensor.pws_tf_period_0_text
    - sensor.pws_tf_period_0_title
    - sensor.pws_tf_period_1_text
    - sensor.pws_tf_period_1_title
    - sensor.pws_tf_period_2_text
    - sensor.pws_tf_period_2_title
    - sensor.pws_stationid
    - sensor.pws_dewpoint_string
    - sensor.pws_heat_index_string
    - sensor.pws_observation_time
    - sensor.pws_wind_degrees
    - sensor.pws_wind_dir
    - sensor.pws_wind_gust_mph
    - sensor.pws_wind_string
    - sensor.pws_precip_1hr_string
    - sensor.pws_precip_today_string
    - sensor.pws_weather
    - sensor.pws_location
    - sensor.bed_therm_mode

# Enables the frontend
frontend:

# View all events in a logbook
logbook:

# Show links to resources in log and frontend
#introduction:

# Allows you to issue voice commands from the frontend
#conversation:

# Track the sun
sun:
  scan_interval: 60

media_player:
  platform: sonos
  interface_addr: 10.0.1.3
  hosts: 
        - 10.0.1.60 # Kitchen

# Some links to some Grafana dashboards
weblink:
  entities:
    - name: Graphs
      url: !secret weblink_grafana_ha
      icon: mdi:chart-line
    - name: System Graphs
      url: !secret weblink_grafana_sys
      icon: mdi:settings

zwave:
  usb_path: /dev/zwave
 # config_path: /home/hass/home-assistant/lib/python3.4/site-packages/libopenzwave-0.3.0b8-py3.4-linux-x86_64.egg/config
  config_path: /home/hass/home-assistant/lib/python3.5/site-packages/libopenzwave-0.3.1-py3.5-linux-x86_64.egg/config
  polling_interval: 90000
  autoheal: false
  customize:
    # Kitchen right
    light.linear_unknown_type4754_id3038_level_2:
      polling_intensity: 1
    light.linear_unknown_type4754_id3038_level_5:
      polling_intensity: 1
    light.linear_unknown_type4754_id3038_level_6:
      polling_intensity: 1
    light.linear_unknown_type4754_id3038_level_10:
      polling_intensity: 1

notify:
  name: email
  platform: smtp
  server: localhost
  port: 25
  sender: !secret notify_sender
  recipient: !secret notify_recipient

# Weather radar from Weather Underground. Retrieved via cron
# https://community.home-assistant.io/t/is-anyone-doing-anything-with-weather-underground/763/101
camera:
    platform: local_file
    file_path: /home/hass/weather.gif
    name: Recent Radar

input_boolean: !include input_boolean.yaml

proximity:
  zone: home
  ignored_zones:
    - work
  devices:
    - device_tracker.all_devices
  tolerance: 250
