# forecast.io
#- platform: forecast
#  api_key: !secret forecast_api_key
#  monitored_conditions:
##      - icon
#      - summary
#      - temperature
#      - wind_speed
##      - precip_type
##      - precip_probability
#      - hourly_summary

# Weather Underground instead
- platform: wunderground
  api_key: !secret wunderground_api_key
  pws_id: !secret wunderground_pws_id

#- platform: template
#  sensors:
#     next24:
#       value_template: '{{ states("sensor.weather_hourly_summary") | lower }}'
#       friendly_name: 'Next 24'

- platform: systemmonitor
  scan_interval: 300
  resources:
   - type: disk_use_percent
     arg: /
   - type: memory_use_percent
   - type: swap_use_percent
   - type: processor_use
   - type: since_last_boot

- platform: command_line
  scan_interval: 300
  name: "CPU Temperature"
  command: "sensors -u k10temp-pci-00c3 | grep temp1_input: | awk '{print $2}'"
#  unit_of_measurement: "°C"
  value_template: '{{ (value | float * (9/5) + 32) | round(1) }}'

- platform: command_line
  scan_interval: 900
  name: "Calendar"
  command: '/home/hass/.local/bin/gcalcli agenda --nocolor --detail_location 00:00 23:59'

- platform: google_travel_time
  origin: !secret google_travel_time_origin
  destination: !secret google_travel_time_destination
  api_key: !secret google_travel_time_api_key
  name: "To work in"
  options:
    mode: "driving"

#- platform: template
#  sensors:
#    bed_therm_mode:
#      value_template: '{{ states.thermostat.stelpro_stzw402_electronic_thermostat_heating_1_11.attributes.current_operation }}'
- platform: template
  sensors:
    bed_therm_setting:
      value_template: '{{ states.climate.stelpro_stzw402_electronic_thermostat_heating_1_11.attributes.temperature }}'

# WUND templates
- platform: template
  sensors:
     pws_weather:
       value_template: '{{ states.sensor.weather_underground_pws.attributes.weather }}'
#     pws_stationid:
#       value_template: '{{ states.sensor.weather_underground_pws.attributes.station_id }}'
#     pws_location:
#       value_template: '{{ states.sensor.weather_underground_pws.attributes.display_location.full }}'
#     pws_elevation:
#       value_template: '{{ states.sensor.weather_underground_pws.attributes.observation_location.elevation }}'
     pws_uv:
       value_template: '{{ states.sensor.weather_underground_pws.attributes.UV }}'
     pws_observation_time:
       value_template: '{{ states.sensor.weather_underground_pws.attributes.observation_time_rfc822 }}'
     pws_relative_humidity:
       value_template: '{{ states.sensor.weather_underground_pws.attributes.relative_humidity }}'
#     pws_wind_degrees:
#       value_template: '{{ states.sensor.weather_underground_pws.attributes.wind_degrees }}'
#     pws_wind_dir:
#       value_template: '{{ states.sensor.weather_underground_pws.attributes.wind_dir }}'
     pws_wind_string:
       value_template: '{{ states.sensor.weather_underground_pws.attributes.wind_string }}'
#     pws_dewpoint_string:
#       value_template: '{{ states.sensor.weather_underground_pws.attributes.dewpoint_string }}'
#     pws_feelslike_string:
#       value_template: '{{ states.sensor.weather_underground_pws.attributes.feelslike_string }}'
#     pws_heat_index_string:
#       value_template: '{{ states.sensor.weather_underground_pws.attributes.heat_index_string }}'
#     pws_precip_1hr_string:
#       value_template: '{{ states.sensor.weather_underground_pws.attributes.precip_1hr_string }}'
#     pws_precip_today_string:
#       value_template: '{{ states.sensor.weather_underground_pws.attributes.precip_today_string }}'
#
#
#  Fahrenheit/Imperial Measurements
#
#     pws_dewpoint_f:
#       value_template: '{{ states.sensor.weather_underground_pws.attributes.dewpoint_f }}'
     pws_temp_f:
       value_template: '{{ states.sensor.weather_underground_pws.attributes.temp_f }}'
     pws_feelslike_f:
       value_template: '{{ states.sensor.weather_underground_pws.attributes.feelslike_f }}'
#     pws_heat_index_f:
#       value_template: '{{ states.sensor.weather_underground_pws.attributes.heat_index_f }}'
#     pws_precip_1hr_in:
#       value_template: '{{ states.sensor.weather_underground_pws.attributes.precip_1hr_in }}'
#     pws_precip_today_in:
#       value_template: '{{ states.sensor.weather_underground_pws.attributes.precip_today_in }}'
     pws_pressure_in:
       value_template: '{{ states.sensor.weather_underground_pws.attributes.pressure_in }}'
     pws_visibility_mi:
       value_template: '{{ states.sensor.weather_underground_pws.attributes.visibility_mi }}'
#     pws_wind_mph:
#       value_template: '{{ states.sensor.weather_underground_pws.attributes.wind_mph }}'
#     pws_wind_gust_mph:
#       value_template: '{{ states.sensor.weather_underground_pws.attributes.wind_gust_mph }}'
    # Forecast
     pws_tf_period_0_text:
        value_template: '{{ states.sensor.weather_underground_pws.attributes.txt_forecast.forecastday.0.fcttext }}'
     pws_tf_period_0_title:
        value_template: '{{ states.sensor.weather_underground_pws.attributes.txt_forecast.forecastday.0.title }}'
     pws_tf_period_1_text:
        value_template: '{{ states.sensor.weather_underground_pws.attributes.txt_forecast.forecastday.1.fcttext }}'
     pws_tf_period_1_title:
        value_template: '{{ states.sensor.weather_underground_pws.attributes.txt_forecast.forecastday.1.title }}'
     pws_tf_period_2_text:
        value_template: '{{ states.sensor.weather_underground_pws.attributes.txt_forecast.forecastday.2.fcttext }}'
     pws_tf_period_2_title:
        value_template: '{{ states.sensor.weather_underground_pws.attributes.txt_forecast.forecastday.2.title }}'
