- alias: 'Turn on light when I get home after sunset'
  trigger:
    platform: state
    entity_id: group.all_devices
    from: 'not_home'
    to: 'home'
  condition:
    condition: and
    conditions:
      - condition: sun
        after: sunset
        after_offset: "-0:55:00"
      - condition: state
        entity_id: group.bedroom_lights
        state: 'off'
      - condition: state
        entity_id: input_boolean.automation_override
        state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: "script.get_home_sunset"

- alias: 'Turn on light near sunset when home'
  trigger:
    platform: sun
    event: sunset
    offset: "-00:55:00"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.bedroom_lights
        state: 'off'
      - condition: state
        entity_id: !secret device_tracker_1
        state: 'home'
      - condition: state
        entity_id: input_boolean.automation_override
        state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: group.bedroom_lights

- alias: 'Turn on stove light upon motion'
  trigger:
    platform: state
    entity_id: sensor.vision_zp3111_multisensor_4in1_burglar_26
    to: '8'
  action:
    service: homeassistant.turn_on
    entity_id: light.linear_lb60z1_dimmable_led_light_bulb_level_22

- alias: 'Turn off stove light upon no motion'
  trigger:
    platform: state
    entity_id: sensor.vision_zp3111_multisensor_4in1_burglar_26
    to: '0'
  action:
    service: homeassistant.turn_off
    entity_id: light.linear_lb60z1_dimmable_led_light_bulb_level_22
